upstream api_service {
    server api:8080; # 'api' é o nome do serviço no docker-compose
    keepalive 32;
}

server {
    listen 80;

    # Healthcheck do próprio Proxy
    location /health {
        return 200 'alive';
        add_header Content-Type text/plain;
    }

    # Rota principal (Proxy reverso)
    location /v1/ {
        proxy_pass http://api_service;
        
        # Headers fundamentais
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        
        # Buffering desligado para baixa latência em APIs
        proxy_buffering off;
    }
}
